-- ASSIGNMENT - 9

-- ID GENERATING THROUGH FUNCTION

CREATE FUNCTION ID_CREATION (@LETTER CHAR(1), @NUMBER INT)
RETURNS VARCHAR(5)
AS 
BEGIN 
	DECLARE @R VARCHAR(5);
	SELECT @R = CASE
					WHEN @NUMBER<10 THEN CONCAT(@LETTER, '000', @NUMBER)
					WHEN @NUMBER<100 THEN CONCAT(@LETTER, '00', @NUMBER)
					WHEN @NUMBER<1000 THEN CONCAT(@LETTER, '0', @NUMBER)
					ELSE NULL
				END;
	RETURN @R

END;

CREATE SEQUENCE SSEQ
AS INT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000
CACHE 5;

CREATE SEQUENCE PSEQ
AS INT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000
CACHE 5;


CREATE SEQUENCE CSEQ
AS INT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000
CACHE 5;

CREATE SEQUENCE OSEQ
AS INT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 1000
CACHE 5;

-- ADD SUPPLIER USING PROCEDURE
 CREATE PROCEDURE AUTO_ADD_SUPPLIER @SNAME VARCHAR(50), @SADD VARCHAR(60), @SCITY VARCHAR(30), @SPHONE VARCHAR(15), @EMAIL VARCHAR(80)
 AS 
 BEGIN
	DECLARE @SID VARCHAR(5)
	SET @SID = DBO.ID_CREATION('S', NEXT VALUE FOR SSEQ)
	INSERT INTO SUPPLIER 
	VALUES(@SID, @SNAME, @SADD, @SCITY, @SPHONE, @EMAIL);

	SELECT * FROM SUPPLIER
	WHERE SID = @SID;
END;

-- ADD PRODUCT USING PROCEDURE
 CREATE PROCEDURE AUTO_ADD_PRODUCT @PDESC VARCHAR(50), @PRICE INT, @CATEGORY VARCHAR(5), @SID CHAR(5)
 AS 
 BEGIN
	DECLARE @PID VARCHAR(5)
	SET @PID = DBO.ID_CREATION('P', NEXT VALUE FOR PSEQ)
	INSERT INTO PRODUCT
	VALUES(@PID, @PDESC, @PRICE, @CATEGORY, @SID);

	SELECT * FROM PRODUCT
	WHERE PID = @PID;
END;

-- ADD CUSTOMER USING PROCEDURE
 CREATE PROCEDURE AUTO_ADD_CUSTOMER @CNAME VARCHAR(50), @ADDRESS VARCHAR(80), @CITY VARCHAR(50), @PHONE CHAR(15), @EMAIL VARCHAR(50), @DOB DATE
 AS 
 BEGIN
	DECLARE @CID VARCHAR(5)
	SET @CID = DBO.ID_CREATION('C', NEXT VALUE FOR CSEQ)
	INSERT INTO CUST
	VALUES(@CID, @CNAME, @ADDRESS, @CITY, @PHONE, @EMAIL, @DOB);

	SELECT * FROM CUST
	WHERE CID = @CID;
END;

-- ADD ORDER USING PROCEDURE
 CREATE PROCEDURE AUTO_ADD_ORDER @CID CHAR(5), @PID CHAR(5), @OQTY INT
 AS 
 BEGIN
	DECLARE @OID VARCHAR(5)
	SET @OID = DBO.ID_CREATION('O', NEXT VALUE FOR OSEQ)
	INSERT INTO ORDERS
	VALUES(@OID, CONVERT(VARCHAR(50), GETDATE(), 111), @CID, @PID, @OQTY);

	SELECT * FROM ORDERS
	WHERE OID = @OID;
END;

AUTO_ADD_ORDER 'C0007', 'P0007', 10

AUTO_ADD_CUSTOMER 'SAI KIRAN', 'FOOD STREET', 'DELHI', '8344126623', 'KIRAN148@GMAIL.COM', '17-JUL-1994'

AUTO_ADD_PRODUCT 'MICROPHONE', 2500, 'IT', 'S0007' 


AUTO_ADD_SUPPLIER 'BHAVANI ELECTRONICS', 'OLD CHOWK', 'MUMBAI', '8865237454', 'BHAVAN3123@GMAIL.COM';
SELECT * FROM PRODUCT;