-- ASSIGNMENT 8
 USE INVENTORY

 -- ADD SUPPLIER USING PROCEDURE
 CREATE PROCEDURE ADD_SUPPLIER @SID CHAR(5), @SNAME VARCHAR(50), @SADD VARCHAR(60), @SCITY VARCHAR(30), @SPHONE VARCHAR(15), @EMAIL VARCHAR(80)
 AS 
 BEGIN
	INSERT INTO SUPPLIER 
	VALUES(@SID, @SNAME, @SADD, @SCITY, @SPHONE, @EMAIL);

	SELECT * FROM SUPPLIER
	WHERE SID = @SID;
END;

-- ADD PRODUCT USING PROCEDURE
 CREATE PROCEDURE ADD_PRODUCT @PID CHAR(5), @PDESC VARCHAR(50), @PRICE INT, @CATEGORY VARCHAR(5), @SID CHAR(5)
 AS 
 BEGIN
	INSERT INTO PRODUCT
	VALUES(@PID, @PDESC, @PRICE, @CATEGORY, @SID);

	SELECT * FROM PRODUCT
	WHERE PID = @PID;
END;

ADD_PRODUCT 'P0016', 'HARD DISK', 4500, 'IT', 'S0005' 

-- ADD CUSTOMER USING PROCEDURE
 CREATE PROCEDURE ADD_CUSTOMER @CID CHAR(5), @CNAME VARCHAR(50), @ADDRESS VARCHAR(80), @CITY VARCHAR(50), @PHONE CHAR(15), @EMAIL VARCHAR(50), @DOB DATE
 AS 
 BEGIN
	INSERT INTO CUST
	VALUES(@CID, @CNAME, @ADDRESS, @CITY, @PHONE, @EMAIL, @DOB);

	SELECT * FROM CUST
	WHERE CID = @CID;
END;

ADD_CUSTOMER 'C0006', 'GAURAV KUMAR', 'COURT STREET', 'MYSORE', '8954126743', 'GAURAVK146@GMAIL.COM', '13-JUN-1993'

-- ADD ORDER USING PROCEDURE
 CREATE PROCEDURE ADD_ORDER @OID CHAR(5), @CID CHAR(5), @PID CHAR(5), @OQTY INT
 AS 
 BEGIN
	INSERT INTO ORDERS
	VALUES(@OID, CONVERT(VARCHAR(50), GETDATE(), 111), @CID, @PID, @OQTY);

	SELECT * FROM ORDERS
	WHERE OID = @OID;
END;

ADD_ORDER 'O0006', 'C0006', 'P0009', 10

SELECT * FROM ORDERS;